version: '3.7'
services:
  service1:
    build: ./service_1
    image: ecalim/service_1:latest
    container_name: service_1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    build: ./service_2
    image: ecalim/service_2:latest
    container_name: service_2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    build: ./service_3
    image: ecalim/service_3:latest
    container_name: service_3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    build: ./service_4
    image: calim/service_4:latest
    container_name: service_4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp