 name: clone git 
 git:
   repo: https://github.com/EfekanCalim1/QA-Practical-Project
   dest: /home/QA-Practical-Project
   update: yes

- name: "make the swarm"
  docker_swarm:
    state: present
- name: "Get swarm info"
  docker_swarm_info:
  register: swarm_info

        
- name: "Get a join token"
  add_host:
    name: "token"
    value: "{{ swarm_info['swarm_facts']['JoinTokens']['Worker'] }}"